CUDA_VISIBLE_DEVICES=1 TOKENIZERS_PARALLELISM=false python run_src/do_generate.py \
    --dataset_name FMT \
    --test_json_filename test_all_with_evidence \
    --api vllm \
    --model_ckpt meta-llama/Llama-3.1-8B-Instruct \
    --note default \
    --half_precision \
    --num_rollouts 4 \
    --tensor_parallel_size 1 \
    --temperature 0.1 \
    --start_idx 0\
    --end_idx 4\
    --verbose  